# Generated by Django 2.2 on 2019-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='build_url',
            field=models.CharField(max_length=100, null=True, verbose_name='构建链接'),
        ),
    ]
